//
// SearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResult: Codable, JSONEncodable, Hashable {

    public var numFound: Int?
    public var start: Int?
    public var docs: [Doc]?

    public init(numFound: Int? = nil, start: Int? = nil, docs: [Doc]? = nil) {
        self.numFound = numFound
        self.start = start
        self.docs = docs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numFound
        case start
        case docs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(numFound, forKey: .numFound)
        try container.encodeIfPresent(start, forKey: .start)
        try container.encodeIfPresent(docs, forKey: .docs)
    }
}

